In [1]:
import pandas as pd

In [ ]:
#series 1d 1 column , DataFrame 2d rxc

In [2]:
#series
pd.Series([1,2,3,4], name = "num")

0    1
1    2
2    3
3    4
Name: num, dtype: int64

In [10]:
di={
    "name":["amaan","rahul","gopi","mohd","keshav","alok"],
    "age":[12,13,14,15,11,12]
}

df = pd.DataFrame(di)
df.head()

     name  age
0   amaan   12
1   rahul   13
2    gopi   14
3    mohd   15
4  keshav   11

In [11]:
# add column
marks=[67,89,67,98,90,81]
df.insert(1,"Marks", marks)
df.head()

     name  Marks  age
0   amaan     67   12
1   rahul     89   13
2    gopi     67   14
3    mohd     98   15
4  keshav     90   11

In [19]:
course = ["BCA","Btech","MBA","MCA","BCA","Btech"]
df["course"] = course
df.sample()

    name  Marks  age course
0  amaan     67   12    BCA

In [37]:
ID =[1,2,3,4,5,6]

In [35]:
do={
    "id":[1,2,3,4,5,6,7],
    "subjects":["maths","english","physics","computer",None,"GenAI","nlp"]

}

In [46]:
df1 = pd.DataFrame(do)
data=pd.merge(df, df1, on="id", how="inner")

In [47]:
data.tail()

     name  Marks  age course  id  subjects
1   rahul     89   13  Btech   2   english
2    gopi     67   14    MBA   3   physics
3    mohd     98   15    MCA   4  computer
4  keshav     90   11    BCA   5       NaN
5    alok     81   12  Btech   6     GenAI

In [62]:
df=pd.read_csv("data/tipsdataset.csv")

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   gender      244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [64]:
df.shape

(244, 7)

In [65]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [66]:
df["gender"].value_counts()   #shows catagorical data

gender
Male      157
Female     87
Name: count, dtype: int64

In [67]:
df.isnull().sum()

total_bill    0
tip           0
gender        0
smoker        0
day           0
time          0
size          0
dtype: int64

In [68]:
data

     name  Marks  age course  id  subjects
0   amaan     67   12    BCA   1     maths
1   rahul     89   13  Btech   2   english
2    gopi     67   14    MBA   3   physics
3    mohd     98   15    MCA   4  computer
4  keshav     90   11    BCA   5       NaN
5    alok     81   12  Btech   6     GenAI

In [69]:
data.isnull().sum()

name        0
Marks       0
age         0
course      0
id          0
subjects    1
dtype: int64

In [70]:
url="https://raw.githubusercontent.com/amaancoding/PBELAI_7/refs/heads/master/DATA/tipsdataset.csv"

In [71]:
pd.read_csv(url)

     total_bill   tip  gender smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [72]:
df

     total_bill   tip  gender smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [76]:
male=df["gender"]=="Male"
smoker=df["smoker"]=="Yes"

In [77]:
df[male & smoker].describe()

       total_bill        tip      size
count   60.000000  60.000000  60.00000
mean    22.284500   3.051167   2.50000
std      9.911845   1.500120   0.89253
min      7.250000   1.000000   1.00000
25%     15.272500   2.000000   2.00000
50%     20.390000   3.000000   2.00000
75%     28.572500   3.820000   3.00000
max     50.810000  10.000000   5.00000

In [78]:
data.isnull().sum()

name        0
Marks       0
age         0
course      0
id          0
subjects    1
dtype: int64

In [ ]:
# use the actual column name
data['subjects'].fillna("missing", inplace=True)

KeyError: 'subject'

In [ ]:
data["subject"]