In [1]:
import pandas as pd

In [ ]:
#series 1d 1 column , DataFrame 2d rxc

In [2]:
#series
pd.Series([1,2,3,4], name = "num")

0    1
1    2
2    3
3    4
Name: num, dtype: int64

In [10]:
di={
    "name":["amaan","rahul","gopi","mohd","keshav","alok"],
    "age":[12,13,14,15,11,12]
}

df = pd.DataFrame(di)
df.head()

     name  age
0   amaan   12
1   rahul   13
2    gopi   14
3    mohd   15
4  keshav   11

In [11]:
# add column
marks=[67,89,67,98,90,81]
df.insert(1,"Marks", marks)
df.head()

     name  Marks  age
0   amaan     67   12
1   rahul     89   13
2    gopi     67   14
3    mohd     98   15
4  keshav     90   11

In [19]:
course = ["BCA","Btech","MBA","MCA","BCA","Btech"]
df["course"] = course
df.sample()

    name  Marks  age course
0  amaan     67   12    BCA

In [37]:
ID =[1,2,3,4,5,6]

In [35]:
do={
    "id":[1,2,3,4,5,6,7],
    "subjects":["maths","english","physics","computer",None,"GenAI","nlp"]

}

In [ ]:
df1 = pd.DataFrame(do)
df1 = pd.DataFrame(do)
pd.merge(df, df1, on="id", how="inner")

KeyError: 'ID'

In [ ]:
data.tail()

In [ ]:
pd.read_csv("data/tipsdataset.csv)

In [ ]:
df.info()

In [ ]:
df.shape

In [ ]:
df.describe()

In [ ]:
df["gender"].value_counts()   #shows catagorical data

In [ ]:
df.isnull().sum()

In [ ]:
data

In [ ]:
data.isnull().sum()

In [ ]:
url=""

In [ ]:
pd.read_csv(url)

In [ ]:
df

In [ ]:
df["gender"]=="Male"
smoker=df["smoker"]=="Yes"

In [ ]:
df[Male & Yes].describe()

In [ ]:
data.isnull().sum()

In [ ]:
data['subject'].fillna("missing",inplace=True)

In [ ]:
data["subject"]